# Generated by Django 5.2.3 on 2025-06-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('tab_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Оператор производственной линии'), (2, 'Технолог'), (3, 'Мастер цеха'), (4, 'Инженер по качеству'), (5, 'Контролер ОТК'), (6, 'Начальник смены'), (7, 'Техник-электроник'), (8, 'Сборщик реле'), (9, 'Администратор системы')], null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'workers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('РЭС52', 'РЭС52'), ('РЭС64А ОС', 'РЭС64А ОС'), ('РЭС78 ОС', 'РЭС78 ОС'), ('РЭК107', 'РЭК107'), ('РЭК 90', 'РЭК 90'), ('РГК37', 'РГК37'), ('РГК 37 Б-В', 'РГК 37 Б-В'), ('РЭН34', 'РЭН34'), ('РЭН 34-Т ОС', 'РЭН 34-Т ОС')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Партии',
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'defect_types',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_array', models.JSONField()),
            ],
            options={
                'db_table': 'workshops',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('РЭС52', 'РЭС52'), ('РЭС64А ОС', 'РЭС64А ОС'), ('РЭС78 ОС', 'РЭС78 ОС'), ('РЭК107', 'РЭК107'), ('РЭК 90', 'РЭК 90'), ('РГК37', 'РГК37'), ('РГК 37 Б-В', 'РГК 37 Б-В'), ('РЭН34', 'РЭН34'), ('РЭН 34-Т ОС', 'РЭН 34-Т ОС')], max_length=20, verbose_name='Серия реле')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.batch', verbose_name='Партия')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.defecttype', verbose_name='Тип дефекта')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.worker', verbose_name='Рабочий')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Дефект производства',
                'verbose_name_plural': 'Дефекты производства',
                'db_table': 'manufacturing_defects',
            },
        ),
    ]
