# Generated by Django 5.2.3 on 2025-06-29 10:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('РЭС52', 'РЭС52'), ('РЭС64А ОС', 'РЭС64А ОС'), ('РЭС78 ОС', 'РЭС78 ОС'), ('РЭК107', 'РЭК107'), ('РЭК 90', 'РЭК 90'), ('РГК37', 'РГК37'), ('РГК 37 Б-В', 'РГК 37 Б-В'), ('РЭН34', 'РЭН34'), ('РЭН 34-Т ОС', 'РЭН 34-Т ОС')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series_array', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Оператор производственной линии'), (2, 'Технолог'), (3, 'Мастер цеха'), (4, 'Инженер по качеству'), (5, 'Контролер ОТК'), (6, 'Начальник смены'), (7, 'Техник-электроник'), (8, 'Сборщик реле'), (9, 'Администратор системы')], null=True)),
                ('tab_number', models.CharField(max_length=10, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.batch', verbose_name='Партия')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.defecttype', verbose_name='Тип дефекта')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Дефект производства',
                'verbose_name_plural': 'Дефекты производства',
            },
        ),
    ]
