# Generated by Django 5.1.2 on 2025-06-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Оператор производственной линии'), (2, 'Технолог'), (3, 'Мастер цеха'), (4, 'Инженер по качеству'), (5, 'Контролер ОТК'), (6, 'Начальник смены'), (7, 'Техник-электроник'), (8, 'Сборщик реле'), (9, 'Администратор системы')], null=True),
        ),
    ]
