# Generated by Django 5.1.2 on 2025-12-12 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0006_remove_airecommendation_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('training', 'Обучение'), ('inactive', 'Неактивен')], max_length=20)),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defects.equipmentmodel')),
            ],
            options={
                'db_table': 'ai_agents',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('continue', 'Продолжить эксплуатацию'), ('retire', 'Списать оборудование')], max_length=20)),
                ('justification', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiagent')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defects.batch')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.equipment')),
            ],
            options={
                'db_table': 'ai_recommendations',
            },
        ),
    ]
