# Generated by Django 5.1.2 on 2025-12-15 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('defects', '0008_rename_dailyproduction_equipmentproduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiagent',
            options={'verbose_name': 'AI агент', 'verbose_name_plural': 'AI агенты'},
        ),
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'ordering': ['-date_created'], 'verbose_name': 'AI рекомендация', 'verbose_name_plural': 'AI рекомендации'},
        ),
        migrations.RemoveField(
            model_name='aiagent',
            name='equipment_model',
        ),
        migrations.AddField(
            model_name='aiagent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiagent',
            name='model_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к модели'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подтвердил'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='probability',
            field=models.FloatField(default=0.0, verbose_name='Вероятность'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='accuracy',
            field=models.FloatField(default=0.0, verbose_name='Точность'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('training', 'Обучение'), ('inactive', 'Неактивен')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiagent', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defects.batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='decision',
            field=models.CharField(choices=[('continue', 'Продолжить эксплуатацию'), ('repair', 'Требуется ремонт'), ('retire', 'Списать оборудование'), ('monitor', 'Усилить мониторинг')], max_length=20, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.equipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='justification',
            field=models.TextField(verbose_name='Обоснование'),
        ),
    ]
